#!/usr/bin/env bash
# SSH client configuration

Host 52.87.231.247
    IdentityFile ~/.ssh/school
    PreferredAuthentications publickey
    PasswordAuthentication no

Host web1
	HostName 52.91.151.166
	User ubuntu
	IdentityFile ~/.ssh/web-01

Host web2
	HostName 35.174.211.254
	User ubuntu
	IdentityFile ~/.ssh/web-02

